version: '3'

services:
  cert-generator:
    build:
      context: ./cert-generator
    volumes:
      - certs-volume:/certs
    networks:
      - mqtt-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"  # Standard MQTT port
      - "8883:8883"  # MQTT over TLS
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - certs-volume:/mosquitto/certs
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - mqtt-network
    depends_on:
      - cert-generator
    restart: unless-stopped

  mqtt-client:
    build:
      context: ./mqtt-client
    container_name: mqtt-client
    volumes:
      - certs-volume:/app/certs
      - ./test-client.py:/app/test-client.py
    networks:
      - mqtt-network
    depends_on:
      - mosquitto

networks:
  mqtt-network:
    driver: bridge

volumes:
  certs-volume:
  mosquitto-data:
  mosquitto-log: